language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install -r test-requirements.txt --upgrade
  - pip install coveralls flake8
script:
  - pytest --cov=polybot
  - flake8
after_success:
  - coveralls
