name: polybot
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.*
  - flask==1.1.*
  - matplotlib>3
  - pandas==1.*
  - pytest
  - pytest-cov
  - pytest-flask
  - flake8
  - pip
  - scikit-learn
  - flake8
  - flask-cors
  - pip:
    - -e .
